# Generated by Django 5.2.5 on 2026-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0003_managerdocument_manager_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdocument',
            name='manager_doc_id',
            field=models.IntegerField(),
        ),
    ]
