# Generated by Django 5.2.5 on 2026-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0004_alter_managerdocument_manager_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdocument',
            name='manager_doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
