# Generated by Django 5.2.7 on 2025-10-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_documents', '0001_initial'),
        ('doctor_personal_details', '0005_alter_doctorpersonaldetails_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordocument',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='doc_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctor_personal_details.doctorpersonaldetails', to_field='contact_number'),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='side',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
