# Generated by Django 5.2.5 on 2025-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordocument',
            name='file_data',
            field=models.TextField(),
        ),
    ]
