# Generated by Django 5.2.5 on 2025-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_documents', '0002_alter_doctordocument_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
