# Generated by Django 5.2.5 on 2025-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('patient', 'Patient'), ('doctor', 'Doctor')], default='user', max_length=10),
        ),
    ]
