# Generated by Django 5.2.5 on 2026-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Yoga Trainer', 'Yoga Trainer'), ('Yoga Doctor', 'Yoga Doctor'), ('Physiotherapist', 'Physiotherapist'), ('Manager', 'Manager')], default='User', max_length=20),
        ),
    ]
