# Generated by Django 5.2.5 on 2025-10-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('yoga_instructor', 'Yoga Trainer'), ('yoga_doctor', 'Yoga Doctor'), ('physiotherapist', 'Physiotherapist')], default='user', max_length=20),
        ),
    ]
