# Generated by Django 5.2.5 on 2025-10-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Yoga Trainer', 'Yoga Trainer'), ('Yoga Doctor', 'Yoga Doctor'), ('Physiotherapist', 'Physiotherapist')], default='User', max_length=20),
        ),
    ]
