# Generated by Django 5.2.5 on 2026-02-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='manager_personal_details.managerpersonaldetails')),
            ],
        ),
    ]
