# Generated by Django 5.2.5 on 2026-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpersonaldetails',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerpersonaldetails',
            name='profile_photo_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
