# Generated by Django 5.2.5 on 2025-11-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_bank_details', '0001_initial'),
        ('trainers_personal_detials', '0002_alter_trainerpersonaldetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbankdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainerbankdetails',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='trainers_personal_detials.trainerpersonaldetails'),
        ),
    ]
