# Generated by Django 5.2.5 on 2025-11-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCertification',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification', serialize=False, to='doctor_personal_details.doctorpersonaldetails')),
                ('highest_degree', models.CharField(max_length=100)),
                ('specializations', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('license_registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('year_of_experience', models.PositiveIntegerField()),
                ('yoga_certified', models.BooleanField(default=False)),
                ('certification_type', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('graduation_certificate', models.TextField(blank=True, null=True)),
                ('experience_letter', models.TextField(blank=True, null=True)),
                ('resume_cv', models.TextField(blank=True, null=True)),
                ('license_pdf', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doctor Certification',
                'verbose_name_plural': 'Doctor Certifications',
                'db_table': 'doctor_certifications',
            },
        ),
    ]
