# Generated by Django 5.2.5 on 2025-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPersonalDetails',
            fields=[
                ('contact_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('spoken_language', models.CharField(blank=True, default='', max_length=100)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
                ('profile_photo_mimetype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Trainer Personal Detail',
                'verbose_name_plural': 'Trainer Personal Details',
                'db_table': 'trainers_personal_details',
            },
        ),
    ]
