# Generated by Django 5.2.5 on 2025-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_personal_detials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpersonaldetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20),
        ),
    ]
