# Generated by Django 5.2.5 on 2025-11-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPersonalDetails',
            fields=[
                ('contact_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('spoken_language', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Doctor Personal Detail',
                'verbose_name_plural': 'Doctor Personal Details',
                'db_table': 'doctors_personal_details',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfilePhoto',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_photo_data', serialize=False, to='doctor_personal_details.doctorpersonaldetails')),
                ('photo_data', models.TextField()),
            ],
        ),
    ]
