# Generated by Django 5.2.5 on 2025-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPersonalDetails',
            fields=[
                ('contact_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('spoken_language', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('hospital', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Doctor Personal Detail',
                'verbose_name_plural': 'Doctor Personal Details',
                'db_table': 'doctors_personal_details',
            },
        ),
    ]
