# Generated by Django 5.2.5 on 2025-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpersonaldetails',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctorpersonaldetails',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctorpersonaldetails',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorpersonaldetails',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
