# Generated by Django 5.2.5 on 2025-10-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpersonaldetails',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
