# Generated by Django 5.2.5 on 2025-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_personal_details', '0002_alter_doctorpersonaldetails_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpersonaldetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
