# Generated by Django 5.2.5 on 2025-11-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_personal_details', '0002_remove_doctorpersonaldetails_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfilePhoto',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_photo_data', serialize=False, to='doctor_personal_details.doctorpersonaldetails')),
                ('photo_data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorpersonaldetails',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='doctorpersonaldetails',
            name='spoken_language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
