# Generated by Django 6.0.5 on 2026-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiopersonaldetails',
            name='profile_photo_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physiopersonaldetails',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
