# Generated by Django 5.2.5 on 2025-10-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_personal_details', '0005_alter_doctorpersonaldetails_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBankDetails',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bank_details', serialize=False, to='doctor_personal_details.doctorpersonaldetails', to_field='contact_number')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(max_length=50)),
                ('bank_qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_bank_details',
            },
        ),
    ]
