# Generated by Django 5.2.5 on 2025-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_bank_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbankdetails',
            name='bank_qr_code_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
