# Generated by Django 5.2.5 on 2025-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_bank_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbankdetails',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='bank_qr_code_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
