# Generated by Django 5.2.5 on 2025-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_bank_details', '0002_doctorbankdetails_bank_qr_code_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbankdetails',
            name='bank_qr_code_filename',
        ),
        migrations.AlterField(
            model_name='doctorbankdetails',
            name='bank_qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
