# Generated by Django 5.2.5 on 2025-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_bank_details', '0003_remove_doctorbankdetails_bank_qr_code_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbankdetails',
            name='bank_qr_code_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorbankdetails',
            name='bank_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
