# Generated by Django 5.2.5 on 2025-10-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_bank_details', '0004_doctorbankdetails_bank_qr_code_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbankdetails',
            name='bank_qr_code_filename',
        ),
    ]
