# Generated by Django 5.2.5 on 2025-10-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_personal_details', '0005_alter_doctorpersonaldetails_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCertification',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification', serialize=False, to='doctor_personal_details.doctorpersonaldetails')),
                ('highest_degree', models.CharField(max_length=255)),
                ('year_of_graduation', models.CharField(max_length=4)),
                ('year_of_experience', models.CharField(max_length=2)),
                ('yoga_certified', models.CharField(max_length=3)),
                ('certification_type', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('graduation_certificate', models.TextField()),
                ('experience_letter', models.TextField(blank=True, null=True)),
                ('resume_cv', models.TextField()),
                ('license_file', models.TextField()),
            ],
        ),
    ]
