# Generated by Django 5.2.5 on 2025-10-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCertification',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification', serialize=False, to='doctor_personal_details.doctorpersonaldetails')),
                ('highest_degree', models.CharField(max_length=255)),
                ('year_of_graduation', models.CharField(max_length=4)),
                ('year_of_experience', models.CharField(max_length=2)),
                ('yoga_certified', models.CharField(max_length=3)),
                ('certification_type', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('graduation_certificate', models.BinaryField(blank=True, null=True)),
                ('graduation_certificate_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_letter', models.BinaryField(blank=True, null=True)),
                ('experience_letter_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_cv', models.BinaryField(blank=True, null=True)),
                ('resume_cv_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.BinaryField(blank=True, null=True)),
                ('license_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
