# Generated by Django 5.2.5 on 2025-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcertification',
            name='experience_letter_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='graduation_certificate_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='license_file_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='resume_cv_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
