# Generated by Django 5.2.5 on 2025-10-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorcertification',
            options={'verbose_name': 'Doctor Certification', 'verbose_name_plural': 'Doctor Certifications'},
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='experience_letter_filename',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='graduation_certificate_filename',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='license',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='license_filename',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='resume_cv_filename',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='license_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='license_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='specializations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='certification_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='experience_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='graduation_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='highest_degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='issuing_authority',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='resume_cv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='year_of_experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='year_of_graduation',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='yoga_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='doctorcertification',
            table='doctor_certifications',
        ),
    ]
