# Generated by Django 5.2.5 on 2026-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcertification',
            old_name='license_registration_number',
            new_name='registration_number',
        ),
        migrations.RenameField(
            model_name='doctorcertification',
            old_name='specializations',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='year_of_experience',
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='work_experience',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
