# Generated by Django 5.2.5 on 2025-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0002_alter_doctorcertification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcertification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorcertification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='issuing_authority',
            field=models.CharField(max_length=255),
        ),
    ]
