# Generated by Django 5.2.7 on 2025-10-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0002_doctorcertification_experience_letter_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcertification',
            old_name='license_file',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='doctorcertification',
            old_name='license_file_filename',
            new_name='license_filename',
        ),
    ]
