# Generated by Django 5.2.5 on 2025-11-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0003_auto_20251107_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcertification',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='doctorcertification',
            name='issue_date',
        ),
    ]
