# Generated by Django 5.2.5 on 2025-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_certification', '0003_rename_license_file_to_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcertification',
            name='graduation_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='resume_cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
