# Generated by Django 5.2.5 on 2025-11-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers_personal_detials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='Optional UPI ID.', max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('SAVING', 'Saving Account'), ('CURRENT', 'Current Account')], max_length=10)),
                ('qr_code', models.BinaryField(blank=True, help_text='QR code image stored as binary data.', null=True)),
                ('qr_code_mimetype', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='trainers_personal_detials.trainerpersonaldetails')),
            ],
            options={
                'verbose_name': 'Trainer Bank Detail',
                'db_table': 'trainers_bank_details',
            },
        ),
    ]
