# Generated by Django 5.2.5 on 2025-11-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers_personal_detials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_degree', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('work_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('yoga_certified', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('certification_type', models.CharField(blank=True, max_length=255)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='trainers_personal_detials.trainerpersonaldetails')),
            ],
            options={
                'verbose_name': 'Trainer Certification',
                'db_table': 'trainers_certifications',
            },
        ),
    ]
