# Generated by Django 5.2.5 on 2026-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdocument',
            name='file_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managerdocument',
            name='file',
            field=models.BinaryField(),
        ),
    ]
