# Generated by Django 5.2.5 on 2026-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0002_managerdocument_file_mimetype_and_more'),
        ('manager_personal_details', '0002_managerpersonaldetails_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdocument',
            name='manager_doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='managerdocument',
            unique_together={('manager', 'manager_doc_id')},
        ),
    ]
