# Generated by Django 5.2.7 on 2025-10-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='otp',
        ),
    ]
