# Generated by Django 5.2.5 on 2026-02-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempManagerPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_id', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date_of_joining', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='temp_manager_profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempManagerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='temp_manager_docs/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_auth.tempmanagerpersonal')),
            ],
        ),
        migrations.CreateModel(
            name='TempManagerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_auth.tempmanagerpersonal')),
            ],
        ),
    ]
