# Generated by Django 5.2.5 on 2026-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_tempmanagerpersonal_tempmanagerdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmanagerdocument',
            name='file_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tempmanagerpersonal',
            name='profile_photo_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempmanagerdocument',
            name='file',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='tempmanagerpersonal',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
