# Generated by Django 5.2.7 on 2025-10-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_remove_adminuser_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_user',
        ),
    ]
