# Generated by Django 5.2.7 on 2025-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_alter_adminuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
