# Generated by Django 5.2.5 on 2026-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_tempmanagerdocument_file_mimetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
