# Generated by Django 5.2.5 on 2025-11-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers_personal_detials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCertification',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification_details', serialize=False, to='trainers_personal_detials.trainerpersonaldetails')),
                ('highest_degree', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('work_experience', models.PositiveIntegerField(blank=True, help_text='Work experience in years', null=True)),
                ('yoga_certified', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('certification_type', models.CharField(blank=True, max_length=255)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Trainer Certification',
                'db_table': 'trainers_certifications',
            },
        ),
    ]
