# Generated by Django 5.2.11 on 2026-04-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('specializations', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_graduation', models.CharField(blank=True, max_length=10, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('is_certified_licensed', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physio_certification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
