# Generated by Django 5.2.11 on 2026-04-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card_front', models.ImageField(blank=True, null=True, upload_to='physio_documentation/aadhar/')),
                ('aadhar_card_back', models.ImageField(blank=True, null=True, upload_to='physio_documentation/aadhar/')),
                ('pancard', models.ImageField(blank=True, null=True, upload_to='physio_documentation/pancard/')),
                ('resume_cv', models.FileField(blank=True, null=True, upload_to='physio_documentation/resume/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='physio_documentation/certificate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physio_documentation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
