# Generated by Django 6.0.5 on 2026-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiodocumentation',
            name='aadhar_card_back_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physiodocumentation',
            name='aadhar_card_front_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physiodocumentation',
            name='certificate_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physiodocumentation',
            name='pancard_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physiodocumentation',
            name='resume_cv_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physiodocumentation',
            name='aadhar_card_back',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiodocumentation',
            name='aadhar_card_front',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiodocumentation',
            name='certificate',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiodocumentation',
            name='pancard',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiodocumentation',
            name='resume_cv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
