# Generated by Django 5.2.5 on 2025-11-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers_personal_detials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(editable=False)),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('RESUME_CV', 'Resume/CV'), ('CERTIFICATION', 'Certification'), ('OTHER', 'Other')], max_length=50)),
                ('side', models.CharField(blank=True, choices=[('FRONT', 'Front'), ('BACK', 'Back')], help_text='Only for documents like Aadhar/PAN card', max_length=10, null=True)),
                ('document_file', models.BinaryField()),
                ('document_mimetype', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trainers_personal_detials.trainerpersonaldetails')),
            ],
            options={
                'verbose_name': 'Trainer Document',
                'db_table': 'trainers_documents',
                'ordering': ['trainer', 'document_id'],
                'unique_together': {('trainer', 'document_id')},
            },
        ),
    ]
