# Generated by Django 5.2.5 on 2025-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerdocument',
            options={'ordering': ['trainer', 'uploaded_at'], 'verbose_name': 'Trainer Document'},
        ),
        migrations.AlterUniqueTogether(
            name='trainerdocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trainerdocument',
            name='document_id',
        ),
    ]
